server:
  port: 8080

Spring:
  profiles:
    active: test


person:
  name: zhangsan
  age: ${random.int}
  happy: false
  birth: 2021/07/17
  maps: {k1: v1,k2: v2}
  list: ["code","music","girl"]
  dog:
    name: tomcat
    age: 5
